# development docker compose file
version: "3.8"
services:
    belief-map-nginx:
        image: nginx:alpine
        volumes:
            - ./data/docker/nginx/dev/conf.d:/etc/nginx/conf.d
            - ./:/app:delegated
        ports:
            - ${WEB_PORT:-80}:80
        environment:
            TZ: Europe/London
        depends_on:
            - belief-map-php-fpm
    belief-map-database:
        restart: unless-stopped
        image: postgres:latest
        volumes:
            - belief-map-data:/var/lib/postgresql/data
        ports:
            - ${DB_PORT:-5432}:5432
        environment:
            TZ: Europe/London
            POSTGRES_USER: postgres
            POSTGRES_DB: belief-map
            POSTGRES_PASSWORD: 12345
    belief-map-php-fpm:
        image: yiisoftware/yii2-php:8.0-fpm
        working_dir: /app
        volumes:
            - ~/.composer-docker/cache:/var/www/.composer/cache:delegated
            - ./:/app:delegated
        environment:
            TZ: Europe/London
            PHP_USER_ID: 1000
        depends_on:
            - belief-map-database    
volumes:
    belief-map-data:
